language: ruby
cache: bundler
before_install:
  - gem install bundler -v '>= 1.5.1'
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
before_script:
  - rake app:db:create
  - rake app:db:test:load
script:
  - "cd spec/dummy && bundle exec rspec spec"
services:
  - elasticsearch